[package]
name = "rust-ceda"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.10.6"
reqwest = { version = "0.12.7", features = ["json"] }
scraper = "0.20.0"
tokio = { version = "1.39.3", features = ["full"] }
